# Generated by Django 5.1.3 on 2025-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCallList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile_No', models.IntegerField()),
                ('City', models.CharField(max_length=1000)),
                ('College_Name', models.CharField(max_length=1000)),
                ('Department', models.CharField(max_length=1000)),
            ],
        ),
    ]
